name: .NET Build Linux

on:
  push:
    branches: [ master ]
    paths:
    - src/**
  pull_request:
    branches: [ master ]
    paths:
    - src/**
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./src
    - name: Run unit tests
      run: dotnet test --configuration Release --no-build
      working-directory: ./src